
/*
 {
    'battery' : "zzz",
    'Ram': 'وحدات التخزين العشوائيه',
    'Laptop': 'الكمبيوتر المحمول',
    'desktop': 'جهاز سطح المكتب',
    'E_card': 'لوحات الكتونيه',
    'lcd-screen': 'شاشات',
    'led': 'لمبات LED',
    'mobile_tablet': 'موبيلات وتابلت',
    'printer_scaner': 'طابعه واسكنر',
    'Video_Cast': 'فيديو كاست',
  };

 'battery',
    'Ram',
    'Laptop',
    'desktop',
    'E_card',
    'lcd-screen',
    'led',
    'mobile_tablet',
    'printer_scaner',
    'Video_Cast',
// */
// class home extends StatelessWidget {
//   List photo = [
//     'power-supply',
//     'camera',
//     'motherboard',
//     'harddrive',
//     'control-unit',
//     'smartphone',
//     'machine',
//     'generator',
//     'solar-power',
//     'server',
//     'ram',
//     'keyboard-and-mouse',
//     'router',
//     'printer',
//     'light-led',
//     'Desktops',
//     'cpu',
//     'speaker',
//     'laptop',
//     'Screens',
//     'Other-materials',
//   ];
//   List namephoto = [
//     'power-supply',
//     'camera',
//     'motherboard',
//     'hard disk',
//     'control-unit',
//     'smartphone',
//     'machine',
//     'generator',
//     'solar-power',
//     'server',
//     'Ram',
//     'keyboard-and-mouse',
//     'router',
//     'printer',
//     'light-led',
//     'Desktops',
//     'cpu',
//     'speaker',
//     'laptop',
//     'Screens',
//     'Other-materials',
//   ];